spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: "coding.email.tester@gmail.com"
    password: xozyjenxhtysrrme
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
